### ISSUE TITLE
Please tag release that is compatible with latest racon

### ISSUE THREAD

**Issue by tillea** [rvaser/thread_pool#3]
Hi,
when trying to compile lates racon (version 1.4.3) with thread_pool 1.0.0 I get

    /build/racon-1.4.3/src/polisher.cpp:366:51: error: 'class thread_pool::ThreadPool' has no member named 'submit'
      366 |         thread_futures.emplace_back(thread_pool_->submit(
          |                                                   ^~~~~~
    /build/racon-1.4.3/src/polisher.cpp: In member function 'virtual void racon::Polisher::find_overlap_breaking_points(std::vector<std::unique_ptr<racon::Overlap> >&)':
    /build/racon-1.4.3/src/polisher.cpp:461:51: error: 'class thread_pool::ThreadPool' has no member named 'submit'
      461 |         thread_futures.emplace_back(thread_pool_->submit(
          |                                                   ^~~~~~
    /build/racon-1.4.3/src/polisher.cpp: In member function 'virtual void racon::Polisher::polish(std::vector<std::unique_ptr<racon::Sequence> >&, bool)':
    /build/racon-1.4.3/src/polisher.cpp:488:51: error: 'class thread_pool::ThreadPool' has no member named 'submit'
      488 |         thread_futures.emplace_back(thread_pool_->submit(
          |                                                   ^~~~~~

The latest commits here seem to provide a member named 'submit' so its just a matter of tagging a release that would match the racon release requirements.  Please do so to help me packaging the latest version for Debian.
Kind regards, Andreas.

**Comment by rvaser** [comment]
Done! By the way, Racon has newer releases at https://github.com/lbcb-sci/racon (which is the new main repository).

Best regards,
Robert

**Comment by tillea** [comment]
On Tue, Sep 17, 2019 at 09:07:03AM -0700, Robert Vaser wrote:
> Done! By the way, Racon has newer releases at https://github.com/lbcb-sci/racon (which is the new main repository).
Thanks for the fast and helpful response as well as the hint to the move of racon.  Unfortunately there is an issue with latest spoa release which I reported in issue #6.
